name: "Test"

on:
    workflow_dispatch:
      inputs:
        environment:
          description: "Environment"
          required: true
          type: choice
          default: dev
          options:
            - dev
            - stg
            - prd
            - nothing
jobs:
  action:
    name: Action
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment: |-
            ${{ fromJSON('[
                    "a",
                    "b",
                    "c",
                    "d"
                ]
            }') }}
    steps:
      - name: Echo
        run: |
          echo ${{ matrix.environment }}
